"""Initial migration

Revision ID: 06ce4644c0e7
Revises: 
Create Date: 2025-08-21 08:47:02.758357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ce4644c0e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('purchase_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('q_reason', sa.String(length=255), nullable=True),
    sa.Column('q_budget', sa.String(length=50), nullable=True),
    sa.Column('q_wait', sa.String(length=50), nullable=True),
    sa.Column('model_prediction', sa.Integer(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('final_user_decision', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_event')
    op.drop_table('user')
    # ### end Alembic commands ###
