"""Add status and decision columns to ProductEvent

Revision ID: 39396154465a
Revises: 6028560e1f47
Create Date: 2025-08-14 18:28:31.205473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39396154465a'
down_revision = '6028560e1f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('decision', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.drop_column('decision')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
