"""Add action_type to ProductEvent

Revision ID: 984a8d4346a4
Revises: 39396154465a
Create Date: 2025-08-14 23:18:15.989184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984a8d4346a4'
down_revision = '39396154465a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.drop_column('action_type')

    # ### end Alembic commands ###
