"""Implement final event funnel with status, decision, and view count

Revision ID: 9897be319a76
Revises: 4929e7f57648
Create Date: 2025-08-15 09:48:58.666700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9897be319a76'
down_revision = '4929e7f57648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_event',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('price_text', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('event_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('decision', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('action_type', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('product_event_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('purchase_event')
    # ### end Alembic commands ###
