"""Add survey columns to PurchaseEvent

Revision ID: b4ca7cba12d0
Revises: 9a6cdd564768
Create Date: 2025-08-15 19:54:17.789535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ca7cba12d0'
down_revision = '9a6cdd564768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('q_budget', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('q_wait', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_event', schema=None) as batch_op:
        batch_op.drop_column('q_wait')
        batch_op.drop_column('q_budget')
        batch_op.drop_column('q_reason')

    # ### end Alembic commands ###
